name = "garde"
main = "src/index.js"
compatibility_date = "2023-08-23"

## PROD

[vars]
ORIGIN = "https://gardeai.com"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "garde-fencing-videos"

[[d1_databases]]
binding = "DB"
database_name = "garde-db"
database_id = "ce77f4f5-73e9-4c99-b7be-877085700dbf"

## DEV

[env.dev.vars]
ORIGIN = "http://localhost:3000"

[[env.dev.r2_buckets]]
binding = "BUCKET"
bucket_name = "dev-garde-fencing-videos"
preview_bucket_name = "dev-garde-fencing-videos"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-garde-db"
database_id = "6c1e3ab3-6f43-4499-afa7-e4325d1c09d1"
preview_database_id = "6c1e3ab3-6f43-4499-afa7-e4325d1c09d1"

