/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function FencerSword(props) {
	const { nodes, materials } = useGLTF("models/fencer_sword.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes["11748_sword_v1_l2_1"].geometry}
					material={materials.Sword_handle}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes["11748_sword_v1_l2_2"].geometry}
					material={materials.Sword_tip}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes["11748_sword_v1_l2_3"].geometry}
					material={materials.Sword_straight_handle}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes["11748_sword_v1_l2_4"].geometry}
					material={materials.Sword_blade}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes["11748_sword_v1_l2_5"].geometry}
					material={materials.Sword_guard}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/fencer_sword.glb");
