/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FencerHelmet(props) {
  const { nodes, materials } = useGLTF('models/fencer_helmet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['11724_helmet_v1_L3_1'].geometry}
          material={materials.helmet_grid}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['11724_helmet_v1_L3_2'].geometry}
          material={materials.helmet_body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['11724_helmet_v1_L3_3'].geometry}
          material={materials.helmet_chrome}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/fencer_helmet.glb')